apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ykre3t6ap-nodejs
  janus-idp.io/tekton: ykre3t6ap-nodejs
  backstage.io/kubernetes-id: ykre3t6ap-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ykre3t6ap-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
