apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ykre3t6ap-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ykre3t6ap-nodejs 
  name: ykre3t6ap-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: ykre3t6ap-nodejs 
